import React, { useEffect, useState, useContext } from 'react';
import { useSelector, useDispatch } from 'react-redux'; import { useNavigate } from 'react-router-dom'; import { AuthContext } from '../context/AuthContext'; import { clearCart } from '../redux/cartSlice';
const blank = { label: 'Home', fullName: '', phone: '', street: '', city: '', state: '', postalCode: '', country: 'India', landmark: '', isDefault: false };
export default function Checkout() {
  const { user } = useContext(AuthContext); const cartItems = useSelector(s => s.cart.cartItems); const dispatch = useDispatch(); const navigate = useNavigate(); const [addresses, setAddresses] = useState([]); const [address, setAddress] = useState(blank); const [saving, setSaving] = useState(false); const total = cartItems.reduce((sum, item) => sum + item.price * item.qty, 0);
  useEffect(() => { if (!user) return navigate('/login'); fetch('/api/auth/profile', { headers: { Authorization: `Bearer ${user.token}` } }).then(r => r.json()).then(data => { const saved = data.addresses || []; setAddresses(saved); const chosen = saved.find(a => a.isDefault) || saved[0]; if (chosen) setAddress({ ...chosen, _id: undefined }); }).catch(() => {}); }, [user, navigate]);
  const change = e => setAddress({ ...address, [e.target.name]: e.target.value });
  const saveAddress = async () => { const res = await fetch('/api/auth/addresses', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${user.token}` }, body: JSON.stringify(address) }); const data = await res.json(); if (!res.ok) return alert(data.message); setAddresses(data); alert('Address saved to your profile.'); };
  const pay = async e => { e.preventDefault(); if (!cartItems.length) return alert('Your cart is empty'); setSaving(true); try { const orderRes = await fetch('/api/payment/order', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${user.token}` }, body: JSON.stringify({ items: cartItems }) }); const order = await orderRes.json(); if (!orderRes.ok) return alert(order.message || 'Unable to start payment'); const rzp = new window.Razorpay({ key: order.key, amount: order.amount, currency: order.currency, name: 'ShopNest', description: 'Secure payment', order_id: order.id, prefill: { name: address.fullName, email: user.email, contact: address.phone }, handler: async response => { setSaving(true); const verify = await fetch('/api/payment/verify', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${user.token}` }, body: JSON.stringify({ ...response, items: cartItems, address }) }); const result = await verify.json(); if (!verify.ok) return alert(result.message || 'Payment verification failed'); dispatch(clearCart()); navigate('/ordersuccess'); }, modal: { ondismiss: () => setSaving(false) }, theme: { color: '#f97316' } }); rzp.open(); } catch { alert('Unable to reach the payment service. Please try again.'); } finally { setSaving(false); } };
  return <div className="checkout-container"><h2>Checkout</h2><div className="checkout-content"><form onSubmit={pay} className="shipping-form"><h3>Delivery address</h3>{addresses.length > 0 && <select onChange={e => { const selected = addresses.find(a => a._id === e.target.value); if (selected) setAddress({ ...selected, _id: undefined }); }}><option value="">Choose a saved address</option>{addresses.map(a => <option key={a._id} value={a._id}>{a.label} — {a.street}, {a.city}</option>)}</select>}<input name="fullName" placeholder="Full name" required value={address.fullName} onChange={change}/><input name="phone" placeholder="Phone number" required value={address.phone} onChange={change}/><input name="street" placeholder="House / street" required value={address.street} onChange={change}/><input name="landmark" placeholder="Landmark (optional)" value={address.landmark} onChange={change}/><input name="city" placeholder="City" required value={address.city} onChange={change}/><input name="state" placeholder="State" value={address.state} onChange={change}/><input name="postalCode" placeholder="PIN code" required value={address.postalCode} onChange={change}/><label><input type="checkbox" checked={address.isDefault} onChange={e => setAddress({...address, isDefault:e.target.checked})}/> Make this my default address</label><button type="button" className="text-button" onClick={saveAddress}>Save this address</button><div className="checkout-summary"><h4>Total to Pay: ₹{total.toFixed(2)}</h4><button className="btn" disabled={saving}>{saving ? 'Preparing secure payment…' : 'Pay securely'}</button></div></form></div></div>;
}
